---@meta

---@class Board @关卡
---方法
---@field GetUpdateDelta fun(self): number @获取距离上一逻辑帧的时间
---@field MousePressing fun(self): boolean @鼠标是否按住（暂停不记录）
---@field SetSun fun(self, value: integer) @设置关卡的阳光值
---@field GetZombies fun(self): table<integer, Zombie> @返回场上所有僵尸
---@field GetZombieById fun(self, id: integer): Zombie? @通过僵尸 id 查询僵尸
---@field AddZombie fun(self, zombie_type: integer, row: integer, from_wave: integer): Zombie @生成一只新的僵尸
---@field AddCoin fun(self, pos: Vec2, coin_type: CoinType, coin_motion: CoinMotion): Coin @生成一只新的僵尸
---@field PosToGridKeepOnBoard fun(self, pos: Vec2): Vec2 @将坐标转换为地图中的棋盘坐标，确保是可用的
---@field GetPlants fun(self): table<integer, Plant> @返回场上所有植物
---@field GetPlantById fun(self, id: integer): Plant? @通过植物 id 查询植物
---@field GetPlantByGrid fun(self, grid: Vec2): (Plant?, Plant?, Plant?, Plant?) @通过棋盘坐标获取对应的植物。分别返回：常规植物、底部植物、外围植物、空中植物。如果同一个位置存在复数植物则返回 id 最大的。
---@field Explode fun(self, pos: Vec2, radius: integer, flag: DamageFlag, sound: GameSound?, particle: Particle?) @在特定位置产生一次爆炸
---@field AddPlant fun(self, grid_pos: Vec2, seed_type: integer): Plant @在指定位置种植一株植物
