---@meta

---别名
    ---@alias ModCallback integer
    ---@alias CallbackFunction fun(...)
    ---@alias Serializable Serializable[]|boolean|number|integer|string|table<Serializable, Serializable>
    ---@alias MouseCode integer
    ---@alias KeyCode integer
    ---@alias RenderLayer integer
    ---@alias CoinType integer
    ---@alias CoinMotion integer

---函数
    ---将日志写入到终端中
    ---@class Log
    ---@field info fun(...: any) @输出信息级别日志
    ---@field warn fun(...: any) @输出警告级别日志
    ---@field error fun(...: any) @输出错误级别日志
    ---@field debug fun(...: any) @输出调试级别日志
    ---@field trace fun(...: any) @输出追踪级别日志
    Log = {}

    ---注册一个模组 
    ---@param name string @模组名称
    ---@return Mod @返回模组对象
    function RegisterMod(name) end

    ---获取游戏类
    ---@return LawnApp @返回游戏对象
    function GetLawnApp() end

---模组类定义
    ---@class Mod @模组
    ---@field name string @模组名称
    ---@field priority integer @模组优先级
    ---@field AddCallback fun(self, callback: ModCallback, function: CallbackFunction) @添加回调函数

    ---@class Vec2 @二维向量
    ---@field x number
    ---@field y number
    ---@field Add fun(self, other: Vec2): Vec2 @向量加法
    ---@field Sub fun(self, other: Vec2): Vec2 @向量减法
    ---@field Mul fun(self, scalar: number): Vec2 @标量乘法
    ---@field Div fun(self, scalar: number): Vec2 @标量除法
    ---@field Dot fun(self, other: Vec2): number @点积（内积）
    ---@field Length fun(self): number @向量长度（模）
    ---@field LengthSquared fun(self): number @向量长度的平方
    ---@field Normalize fun(self): Vec2 @归一化（返回单位向量）
    ---@field Distance fun(self, other: Vec2): number @计算两点之间的距离
    ---@field DistanceSquared fun(self, other: Vec2): number @计算两点之间距离的平方
    ---@field Lerp fun(self, other: Vec2, t: number): Vec2 @线性插值
    ---@field Angle fun(self): number @计算向量的角度（弧度）
    ---@field AngleTo fun(self, other: Vec2): number @计算从当前点到另一点的角度
    ---@field Rotate fun(self, angle: number): Vec2 @旋转向量（angle为弧度）
    ---@field Cross fun(self, other: Vec2): number @叉积（2D叉积返回标量）
    ---@field Reflect fun(self, normal: Vec2): Vec2 @反射向量（根据法线反射）
    ---@field New fun(x: number, y: number): Vec2 @创建二位向量
    ---@field Zero fun(): Vec2 @创建零向量
    Vec2 = {}

    ---@class Rect2 @二维矩形
    ---@field x number
    ---@field y number
    ---@field width number
    ---@field height number
    ---@field pos Vec2
    ---@field size Vec2
    ---@field New fun(x: number, y: number, w: number, h: number): Rect2
    ---@field Zero fun(): Rect2
    ---@field Contains fun(self, pos: Vec2): boolean @判断一个二维向量是否在自身范围内
    ---@field Collides fun(self, other: Rect2): boolean @判断自身是否与给定矩形碰撞（相交）
    Rect2 = {}

    ---@class Color @颜色
    ---@field red integer @0-255之外的值无效
    ---@field green integer @0-255之外的值无效
    ---@field blue integer @0-255之外的值无效
    ---@field alpha integer @0-255之外的值无效
    ---@field New fun(red: integer, green: integer, blue: integer, alpha: integer): Color
    Color = {}


---游戏类定义
    ---@class LawnApp @游戏
    ---字段
    ---@field tigger fun(flag: string) @调试保留
    ---方法
    ---@field GetWindowSize fun(self): Vec2 @获取窗口尺寸
    ---@field GetMousePos fun(self): Vec2 @获取鼠标坐标
    ---@field GetBoard fun(self): Board? @获取关卡，如果还未创建则为空

    ---@class Board @关卡
    ---方法
    ---@field GetUpdateDelta fun(self): number @获取距离上一逻辑帧的时间
    ---@field MousePressing fun(self): boolean @鼠标是否按住（暂停不记录）
    ---@field SetSun fun(self, value: integer) @设置关卡的阳光值
    ---@field GetZombies fun(self): table<integer, Zombie> @返回场上所有僵尸
    ---@field GetZombieById fun(self, id: integer): Zombie? @通过僵尸 id 查询僵尸
    ---@field AddZombie fun(self, zombie_type: integer, row: integer, from_wave: integer): Zombie @生成一只新的僵尸
    ---@field AddCoin fun(self, pos: Vec2, coin_type: CoinType, coin_motion: CoinMotion): Coin @生成一只新的僵尸
    ---@field PosToGridKeepOnBoard fun(self, pos: Vec2): Vec2 @将坐标转换为地图中的棋盘坐标，确保是可用的

    ---@class Graphics @图形
    ---@field SetLayer fun(self, layer: RenderLayer) @设置渲染层
    ---@field SetColor fun(self, color: Color) @设置绘图颜色
    ---@field DrawRect fun(self, rect: Rect2) @绘制一个空心矩形
    ---@field FillRect fun(self, rect: Rect2) @绘制一个实心矩形

    ---@class Zombie @僵尸
    ---方法
    ---@field SetAttr fun(self, key: string, value: Serializable) @设定自定义僵尸数据
    ---@field GetAttr fun(self, key: string): Serializable? @获取自定义僵尸数据
    ---@field RemoveAttr fun(self, key: string) @删除自定义僵尸数据
    ---@field IsValid fun(self): boolean @这个僵尸是否在内存中有效
    ---@field GetPos fun(self): Vec2 @获取僵尸坐标
    ---@field SetPos fun(self, pos: Vec2) @设定僵尸坐标
    ---@field SetPosRaw fun(self, pos: Vec2) @设定僵尸坐标，不自动设定所在行，尽可能避免用这个因为会导致僵尸可能非预期的表现
    ---@field GetRow fun(self): integer @获取僵尸所在的行
    ---@field SetRow fun(self, row: integer) @设定僵尸所在的行
    ---@field GetHitbox fun(self): Rect2 @获取僵尸命中判定框
    ---@field GetHitboxRelative fun(self): Rect2 @获取僵尸命中判定框，原点为僵尸坐标
    ---@field GetAtkbox fun(self): Rect2 @获取僵尸攻击判定框
    ---@field GetAtkboxRelative fun(self): Rect2 @获取僵尸攻击判定框，原点为僵尸坐标
    ---
    ---@field GetBodyHp fun(self): integer @获取僵尸本体血量
    ---@field SetBodyHp fun(self, hp: integer) @设定僵尸本体血量
    ---@field GetBodyHpMax fun(self): integer @获取僵尸本体血量上限
    ---@field SetBodyHpMax fun(self, hp_max: integer) @设定僵尸本体血量上限
    ---
    ---@field GetHelmetHp fun(self): integer @获取僵尸头部护具血量
    ---@field SetHelmetHp fun(self, hp: integer) @设定僵尸头部护具血量
    ---@field GetHelmetHpMax fun(self): integer @获取僵尸头部护具血量上限
    ---@field SetHelmetHpMax fun(self, hp_max: integer) @设定僵尸头部护具血量上限
    ---
    ---@field GetShieldHp fun(self): integer @获取僵尸身前护具血量
    ---@field SetShieldHp fun(self, hp: integer) @设定僵尸身前护具血量
    ---@field GetShieldHpMax fun(self): integer @获取僵尸身前护具血量上限
    ---@field SetShieldHpMax fun(self, hp_max: integer) @设定僵尸身前护具血量上限

    ---@class Coin @掉落物


---回调参数定义
    ---AT_NEW_COIN
    ---@class NewCoinArgs
    ---@field GetPos fun(self): Vec2 @获取掉落物坐标
    ---@field SetPos fun(self, pos: Vec2) @设定掉落物坐标
    ---@field GetCoinType fun(self): integer @获取掉落物类型
    ---@field SetCoinType fun(self, coin_type: CoinType) @设定掉落物类型
    ---@field GetCoinMotion fun(self): integer @获取掉落物运动方式
    ---@field SetCoinMotion fun(self, coin_motion: CoinMotion) @设定掉落物运动方式

    ---AT_NEW_ZOMBIE
    ---@class ArgsNewZombie
    ---@field row integer @僵尸所在的行
    ---@field zombie_type integer @僵尸的类型
    ---@field from_wave integer @僵尸来自的波次


---枚举
    ---@class ModCallbacks @回调点
    ---回调分类
    ---@field AT_DRAW ModCallback @渲染与绘制
        ---
        ---回调函数签名
        ---- `fun(g: Graphics)`
        ---
        ---参数
        ---- `g` : 图形类
    ---@field AT_GAME_KEY_DOWN ModCallback @游戏层面按键按下
        ---
        ---回调函数签名
        ---- `fun(keycode: KeyCode): boolean?`
        ---
        ---参数
        ---- `keycode` : 按下的键码
        ---
        ---返回值
        ---- 如果是 `true` 则会消费此次事件
    ---@field AT_GAME_KEY_UP ModCallback @游戏层面按键松开
        ---
        ---回调函数签名
        ---- `fun(keycode: KeyCode): boolean?`
        ---
        ---参数
        ---- `keycode` : 松开的键码
        ---
        ---返回值
        ---- 如果是 `true` 则会消费此次事件
    ---@field AT_BOARD_UPDATE ModCallback @游戏关卡更新
        ---
        ---回调函数签名
        ---- `fun(delta: number)`
        ---
        ---参数
        ---- `delta` : 距离上一逻辑帧过去的时间（秒）
    ---@field AT_BOARD_KEY_DOWN ModCallback @游戏关卡内按键按下
        ---
        ---回调函数签名
        ---- `fun(keycode: KeyCode): boolean?`
        ---
        ---参数
        ---- `keycode` : 按下的键码
        ---
        ---返回值
        ---- 如果是 `true` 则会消费此次事件
    ---@field AT_BOARD_KEY_UP ModCallback @游戏关卡内按键松开
        ---
        ---回调函数签名
        ---- `fun(keycode: KeyCode): boolean?`
        ---
        ---参数
        ---- `keycode` : 松开的键码
        ---
        ---返回值
        ---- 如果是 `true` 则会消费此次事件
    ---@field AT_BOARD_MOUSE_DOWN ModCallback @游戏关卡内鼠标点击
        ---
        ---回调函数签名
        ---- `fun(mousecode: MouseCode, pos: Vec2): boolean?`
        ---
        ---参数
        ---- `mousecode` : 按下的鼠标点击代码
        ---- `pos` : 鼠标点击的坐标
        ---
        ---返回值
        ---- 如果是 `true` 则会消费此次事件
    ---@field AT_BOARD_MOUSE_UP ModCallback @游戏关卡内鼠标松开
        ---
        ---回调函数签名
        ---- `fun(mousecode: MouseCode, pos: Vec2): boolean?`
        ---
        ---参数
        ---- `mousecode` : 松开的鼠标点击代码
        ---- `pos` : 鼠标点击的坐标
        ---
        ---返回值
        ---- 如果是 `true` 则会消费此次事件
    ---@field AT_NEW_COIN ModCallback @游戏关卡生成掉落物，fun(args: NewCoinArgs)
    ---@field AT_NEW_ZOMBIE ModCallback @游戏关卡生成僵尸，fun(args: NewZombieArgs)
    ---@field AT_ZOMBIE_INIT ModCallback @僵尸初始化，fun(zombie: Zombie)
    ---@field AT_ZOMBIE_DIE ModCallback @僵尸死亡，函数内此僵尸仍然被视为有效，自定数据将在所有此类回调函数结束后被清理
        ---
        ---回调函数签名
        ---- `fun(zombie: Zombie)`
        ---
        ---参数
        ---- `zombie` : 死亡的僵尸
    ---@field AT_ZOMBIE_UPDATE ModCallback @僵尸更新，fun(zombie: Zombie)
    ModCallbacks = {}

    ---@class CoinTypes @掉落物类型
    ---@field SILVER_COIN CoinType @银币
    ---@field GOLD_COIN CoinType @金币
    ---@field DIAMOND CoinType @钻石
    ---@field SUN CoinType @太阳
    ---@field SMALL_SUN CoinType @小太阳
    ---@field LARGE_SUN CoinType @大太阳
    ---@field SEED_PACKET CoinType @植物卡片
    ---@field TROPHY CoinType @奖杯
    ---@field SHOVEL CoinType @铲子
    ---@field ALMANAC CoinType @图鉴
    ---@field KEY CoinType @钥匙
    ---@field VASE CoinType @花瓶
    ---@field WATERING_CAN CoinType @洒水壶
    ---@field SANDWICH CoinType @三明治
    ---@field NOTE CoinType @便条
    ---@field VANISH_PLACEHOLDER CoinType @立即消失(占位)
    ---@field SEEDLING_GIFT CoinType @花苗礼盒
    ---@field COIN_BAG CoinType @金币袋
    ---@field GIFT_BOX_PERSISTENT CoinType @礼盒(不消失)
    ---@field COIN_BAG_PERSISTENT CoinType @金币袋(不消失)
    ---@field SILVER_TROPHY CoinType @银奖杯
    ---@field GOLD_TROPHY CoinType @金奖杯
    ---@field CHOCOLATE CoinType @巧克力
    ---@field CHOCOLATE_PERSISTENT CoinType @巧克力(不消失)
    ---@field GIFT_BOX_MINI_GAMES CoinType @礼品盒(小游戏)
    ---@field GIFT_BOX_PUZZLE CoinType @礼品盒(解密模式)
    ---@field GIFT_BOX_SURVIVAL CoinType @礼品盒(生存模式)
    CoinTypes = {}

    ---@class CoinMotions @掉落物运动方式
    ---@field DROP_FROM_XY CoinMotion @从坐标落下
    ---@field SLOW_DROP_FROM_XY CoinMotion @从坐标缓慢落下
    ---@field POP_FROM_BACK CoinMotion @从后方跳出
    ---@field FAST_POP_FROM_BACK CoinMotion @从后方快速跳出
    ---@field COLLECT_IMMEDIATELY CoinMotion @直接收集
    ---@field AUTO_COLLECT_LATER CoinMotion @稍后自动收集
    ---@field POP_FROM_RIGHT CoinMotion @从屏幕右侧蹦出
    ---@field SPAWN_IN_SEED_SLOT CoinMotion @在卡槽栏生成
    CoinMotions = {}

    ---@class RenderLayers @渲染层
    ---@field Debug RenderLayer @调试层，会尽可能在所有层上渲染
    ---@field UI RenderLayer @UI层，会在游戏UI绘制后渲染
    ---@field Board RenderLayer @关卡层，会在关卡元素绘制后渲染
    RenderLayers = {}

    ---@class MouseCodes @鼠标点击代码
    ---@field L_CLICK MouseCode @鼠标左键
    ---@field L_DOUBLE_CLICK MouseCode @鼠标左键双击
    ---@field R_CLICK MouseCode @鼠标右键
    ---@field R_DOUBLE_CLICK MouseCode @鼠标右键双击
    ---@field M_CLICK MouseCode @鼠标中键
    MouseCodes = {}

    ---@class KeyCodes @键码
    ---@field MODIFIERS KeyCode @用于从键值中提取修饰键的位掩码
    ---@field NONE KeyCode @没有按键按下
    ---@field L_BUTTON KeyCode @鼠标左键
    ---@field R_BUTTON KeyCode @鼠标右键
    ---@field LR_BUTTON KeyCode @左右键一起按
    ---@field M_BUTTON KeyCode @鼠标中键（三键鼠标）
    ---@field X_BUTTON_1 KeyCode @第一个 X 鼠标键（五键鼠标）
    ---@field X_BUTTON_2 KeyCode @第二个 X 鼠标键（五键鼠标）
    ---@field LMR_BUTTON KeyCode @左中右键一起按
    ---@field BACK KeyCode @BACKSPACE 键
    ---@field TAB KeyCode @TAB 键
    ---@field LINE_FEED KeyCode @LINEFEED 键
    ---@field CLEAR KeyCode @CLEAR 键
    ---@field ENTER KeyCode @ENTER 键
    ---@field RETURN KeyCode @RETURN 键
    ---@field SHIFT_KEY KeyCode @SHIFT 键
    ---@field CONTROL_KEY KeyCode @CTRL 键
    ---@field MENU KeyCode @ALT 键
    ---@field PAUSE KeyCode @PAUSE 键
    ---@field CAPITAL KeyCode @CAPS LOCK 键
    ---@field CAPS_LOCK KeyCode @CAPS LOCK 键
    ---@field HANGUEL_MODE KeyCode @IME Hanguel 模式键（为兼容性而保留；请使用 HangulMode）
    ---@field HANGUL_MODE KeyCode @IME Hangul 模式键
    ---@field KANA_MODE KeyCode @IME Kana 模式键
    ---@field JUNJA_MODE KeyCode @IME Junja 模式键
    ---@field FINAL_MODE KeyCode @IME Final 模式键
    ---@field HANJA_MODE KeyCode @IME Hanja 模式键
    ---@field KANJI_MODE KeyCode @IME Kanji 模式键
    ---@field ESCAPE KeyCode @ESC 键
    ---@field IME_CONVERT KeyCode @IME 转换键
    ---@field IME_NONCONVERT KeyCode @IME 非转换键
    ---@field IME_ACCEPT KeyCode @IME 接受键，取代了 IMEAceept
    ---@field IME_ACEEPT KeyCode @IME 接受键已过时，请改用 IMEAccept
    ---@field IME_MODE_CHANGE KeyCode @IME 模式更改键
    ---@field SPACE KeyCode @SPACEBAR（空格）键
    ---@field PAGE_UP KeyCode @PAGE UP（上翻页）键
    ---@field PRIOR KeyCode @PAGE UP（上翻页）键
    ---@field NEXT KeyCode @PAGE DOWN（下翻页）键
    ---@field PAGE_DOWN KeyCode @PAGE DOWN（下翻页）键
    ---@field END KeyCode @END 键
    ---@field HOME KeyCode @HOME 键
    ---@field LEFT KeyCode @LEFT ARROW（左箭头）键
    ---@field UP KeyCode @UP ARROW（上箭头）键
    ---@field RIGHT KeyCode @RIGHT ARROW（右箭头）键
    ---@field DOWN KeyCode @DOWN ARROW（下箭头）键
    ---@field SELECT KeyCode @SELECT 键
    ---@field PRINT KeyCode @PRINT 键
    ---@field EXECUTE KeyCode @EXECUTE 键
    ---@field PRINT_SCREEN KeyCode @PRINT SCREEN（打印屏幕）键
    ---@field SNAPSHOT KeyCode @PRINT SCREEN（打印屏幕）键
    ---@field INSERT KeyCode @INS（插入）键
    ---@field DELETE KeyCode @DEL（删除）键
    ---@field HELP KeyCode @HELP（帮助）键
    ---@field D0 KeyCode @0 键
    ---@field D1 KeyCode @1 键
    ---@field D2 KeyCode @2 键
    ---@field D3 KeyCode @3 键
    ---@field D4 KeyCode @4 键
    ---@field D5 KeyCode @5 键
    ---@field D6 KeyCode @6 键
    ---@field D7 KeyCode @7 键
    ---@field D8 KeyCode @8 键
    ---@field D9 KeyCode @9 键
    ---@field A KeyCode @A 键
    ---@field B KeyCode @B 键
    ---@field C KeyCode @C 键
    ---@field D KeyCode @D 键
    ---@field E KeyCode @E 键
    ---@field F KeyCode @F 键
    ---@field G KeyCode @G 键
    ---@field H KeyCode @H 键
    ---@field I KeyCode @I 键
    ---@field J KeyCode @J 键
    ---@field K KeyCode @K 键
    ---@field L KeyCode @L 键
    ---@field M KeyCode @M 键
    ---@field N KeyCode @N 键
    ---@field O KeyCode @O 键
    ---@field P KeyCode @P 键
    ---@field Q KeyCode @Q 键
    ---@field R KeyCode @R 键
    ---@field S KeyCode @S 键
    ---@field T KeyCode @T 键
    ---@field U KeyCode @U 键
    ---@field V KeyCode @V 键
    ---@field W KeyCode @W 键
    ---@field X KeyCode @X 键
    ---@field Y KeyCode @Y 键
    ---@field Z KeyCode @Z 键
    ---@field L_WIN KeyCode @左 Windows 徽标键（Microsoft 自然键盘）
    ---@field R_WIN KeyCode @右 Windows 徽标键（Microsoft 自然键盘）
    ---@field APPS KeyCode @应用程序键（Microsoft 自然键盘）
    ---@field SLEEP KeyCode @计算机睡眠键
    ---@field NUM_PAD_0 KeyCode @数字键盘上的 0 键
    ---@field NUM_PAD_1 KeyCode @数字键盘上的 1 键
    ---@field NUM_PAD_2 KeyCode @数字键盘上的 2 键
    ---@field NUM_PAD_3 KeyCode @数字键盘上的 3 键
    ---@field NUM_PAD_4 KeyCode @数字键盘上的 4 键
    ---@field NUM_PAD_5 KeyCode @数字键盘上的 5 键
    ---@field NUM_PAD_6 KeyCode @数字键盘上的 6 键
    ---@field NUM_PAD_7 KeyCode @数字键盘上的 7 键
    ---@field NUM_PAD_8 KeyCode @数字键盘上的 8 键
    ---@field NUM_PAD_9 KeyCode @数字键盘上的 9 键
    ---@field MULTIPLY KeyCode @乘法键
    ---@field ADD KeyCode @加法键
    ---@field SEPARATOR KeyCode @分隔符键
    ---@field SUBTRACT KeyCode @减法键
    ---@field DECIMAL KeyCode @小数点键
    ---@field DIVIDE KeyCode @除法键
    ---@field F1 KeyCode @F1 键
    ---@field F2 KeyCode @F2 键
    ---@field F3 KeyCode @F3 键
    ---@field F4 KeyCode @F4 键
    ---@field F5 KeyCode @F5 键
    ---@field F6 KeyCode @F6 键
    ---@field F7 KeyCode @F7 键
    ---@field F8 KeyCode @F8 键
    ---@field F9 KeyCode @F9 键
    ---@field F10 KeyCode @F10 键
    ---@field F11 KeyCode @F11 键
    ---@field F12 KeyCode @F12 键
    ---@field F13 KeyCode @F13 键
    ---@field F14 KeyCode @F14 键
    ---@field F15 KeyCode @F15 键
    ---@field F16 KeyCode @F16 键
    ---@field F17 KeyCode @F17 键
    ---@field F18 KeyCode @F18 键
    ---@field F19 KeyCode @F19 键
    ---@field F20 KeyCode @F20 键
    ---@field F21 KeyCode @F21 键
    ---@field F22 KeyCode @F22 键
    ---@field F23 KeyCode @F23 键
    ---@field F24 KeyCode @F24 键
    ---@field NUM_LOCK KeyCode @NUM LOCK 键
    ---@field SCROLL KeyCode @SCROLL LOCK 键
    ---@field L_SHIFT_KEY KeyCode @左 SHIFT 键
    ---@field R_SHIFT_KEY KeyCode @右 SHIFT 键
    ---@field L_CONTROL_KEY KeyCode @左 CTRL 键
    ---@field R_CONTROL_KEY KeyCode @右 CTRL 键
    ---@field L_MENU KeyCode @左 ALT 键
    ---@field R_MENU KeyCode @右 ALT 键
    ---@field BROWSER_BACK KeyCode @浏览器后退键
    ---@field BROWSER_FORWARD KeyCode @浏览器前进键
    ---@field BROWSER_REFRESH KeyCode @浏览器刷新键
    ---@field BROWSER_STOP KeyCode @浏览器停止键
    ---@field BROWSER_SEARCH KeyCode @浏览器搜索键
    ---@field BROWSER_FAVORITES KeyCode @浏览器收藏夹键
    ---@field BROWSER_HOME KeyCode @浏览器主页键
    ---@field VOLUME_MUTE KeyCode @静音键
    ---@field VOLUME_DOWN KeyCode @降低音量键
    ---@field VOLUME_UP KeyCode @增大音量键
    ---@field MEDIA_NEXT_TRACK KeyCode @媒体下一曲键
    ---@field MEDIA_PREVIOUS_TRACK KeyCode @媒体上一曲键
    ---@field MEDIA_STOP KeyCode @媒体停止键
    ---@field MEDIA_PLAY_PAUSE KeyCode @媒体播放/暂停键
    ---@field LAUNCH_MAIL KeyCode @启动邮件键
    ---@field SELECT_MEDIA KeyCode @选择媒体键
    ---@field LAUNCH_APPLICATION_1 KeyCode @启动应用程序一键
    ---@field LAUNCH_APPLICATION_2 KeyCode @启动应用程序二键
    ---@field OEM_1 KeyCode @OEM 1 键
    ---@field OEM_SEMICOLON KeyCode @US 标准键盘上的 OEM 分号键
    ---@field OEM_PLUS KeyCode @任何国家/地区键盘上的 OEM 加号键
    ---@field OEM_COMMA KeyCode @任何国家/地区键盘上的 OEM 逗号键
    ---@field OEM_MINUS KeyCode @任何国家/地区键盘上的 OEM 减号键
    ---@field OEM_PERIOD KeyCode @任何国家/地区键盘上的 OEM 句点键
    ---@field OEM_2 KeyCode @OEM 2 键
    ---@field OEM_QUESTION KeyCode @US 标准键盘上的 OEM 问号键
    ---@field OEM_3 KeyCode @OEM 3 键
    ---@field OEM_TILDE KeyCode @US 标准键盘上的 OEM 波浪号键
    ---@field OEM_4 KeyCode @OEM 4 键
    ---@field OEM_OPEN_BRACKETS KeyCode @US 标准键盘上的 OEM 左中括号键
    ---@field OEM_5 KeyCode @OEM 5 键
    ---@field OEM_PIPE KeyCode @US 标准键盘上的 OEM 竖线键
    ---@field OEM_6 KeyCode @OEM 6 键
    ---@field OEM_CLOSE_BRACKETS KeyCode @US 标准键盘上的 OEM 右中括号键
    ---@field OEM_7 KeyCode @OEM 7 键
    ---@field OEM_QUOTES KeyCode @US 标准键盘上的 OEM 单引号/双引号键
    ---@field OEM_8 KeyCode @OEM 8 键
    ---@field OEM_102 KeyCode @OEM 102 键
    ---@field OEM_BACKSLASH KeyCode @RT 102 键键盘上的 OEM 尖括号或反斜杠键
    ---@field PROCESS_KEY KeyCode @PROCESS KEY 键
    ---@field PACKET KeyCode @用于传递 Unicode 字符，如同它们是按键一样
    ---@field ATTN KeyCode @ATTN 键
    ---@field CRSEL KeyCode @CRSEL 键
    ---@field EXSEL KeyCode @EXSEL 键
    ---@field ERASE_EOF KeyCode @ERASE EOF 键
    ---@field PLAY KeyCode @PLAY 键
    ---@field ZOOM KeyCode @ZOOM 键
    ---@field NO_NAME KeyCode @保留供将来使用的常量
    ---@field PA1 KeyCode @PA1 键
    ---@field OEM_CLEAR KeyCode @CLEAR 键
    ---@field CODE KeyCode @用于从键值中提取键码的位掩码
    ---@field SHIFT KeyCode @SHIFT 修饰键
    ---@field CONTROL KeyCode @CTRL 修饰键
    ---@field ALT KeyCode @ALT 修饰键
    KeyCodes = {}