---@meta

---@alias ModCallback integer
---@alias CallbackFunction fun(...)
---@alias Serializable Serializable[]|boolean|number|integer|string|table<Serializable, Serializable>
---@alias MouseCode integer
---@alias KeyCode integer
---@alias RenderLayer integer
---@alias CoinType integer
---@alias CoinMotion integer
---@alias GameSound integer
---@alias DamageFlag integer
