---@meta

---注册一个模组 
---@param name string @模组名称
---@return Mod @返回模组对象
function RegisterMod(name) end

---获取游戏类
---@return LawnApp @返回游戏对象，一定能够获取。
function GetLawnApp() end

---@type Log
Log = ...
---@type Vec2
Vec2 = ...
---@type Rect2
Rect2 = ...
---@type Color
Color = ...

---@type CoinTypes
CoinTypes = ...
---@type CoinMotions
CoinMotions = ...
---@type RenderLayers
RenderLayers = ...
---@type MouseCodes
MouseCodes = ...
---@type KeyCodes
KeyCodes = ...
---@type ModCallbacks
ModCallbacks = ...
---@type GameSounds
GameSounds = ...
---@type DamageFlags
DamageFlags = ...
---@type Particles
Particles = ...
